// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzuytqpnmpqfrxahkqts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dXl0cXBubXBxZnJ4YWhrcXRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MDg3OTUsImV4cCI6MjA3NTE4NDc5NX0.EiPD3Um_h6OQaJRllhjhUpLWjKgR2ZVaaseE5BCjfZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});